### ISSUE TITLE
when file name is in number

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#100]
파일 명이 숫자일 때 rm 와 touch 테스트 해봤는데 cmd 작동 안하고 fsanitize에서 터지네요.
![Screen Shot 2021-09-21 at 2 06 26 PM](https://user-images.githubusercontent.com/83805691/134118169-2dd8bbf5-680b-42b5-8a54-28b65b82c305.png)
<img width="804" alt="132890803-5659a5d4-08e2-4fc8-b73b-9b801433d5eb" src="https://user-images.githubusercontent.com/83805691/134118186-99405de3-4f76-4b90-bb8b-d0b0108c763a.png">
![Screen Shot 2021-09-21 at 2 07 04 PM](https://user-images.githubusercontent.com/83805691/134118193-071b54f4-74fc-43db-972f-7e8aed31566d.png)

방금 sleep 도 해봤는데 sleep도 터지네요
<img width="554" alt="Screen Shot 2021-09-21 at 2 45 44 PM" src="https://user-images.githubusercontent.com/83805691/134118274-112a6a28-afca-43ac-b922-6bf69fa87a34.png">

`make_cmds` 함수에서 숫자가 인자로 들어올 때 문제 발생하는 것 같습니다. 화이팅~~!

**Comment by yongjulejule** [comment]
잉 슬립 어제도 해봤던거 같은데 파이프로 넘겨줬던가? 암튼 감사합니다 코드 좀 봐야겠네욤

**Comment by yongjulejule** [comment]
<img width="634" alt="Screen Shot 2021-09-22 at 9 06 23 AM" src="https://user-images.githubusercontent.com/79127797/134263314-ecd16d2b-3a8d-4b6f-9782-4b616a26e3eb.png">

지한님 저거 ls 1 입력하면 한 줄 그대로 넘어오는거 아니였어요??? @42ghan

**Comment by 42ghan** [comment]
아 저런... 저게 저렇게 됐군요 ㅋㅋㅋㅋㅋ 머쓱
곧 고쳐서 PR 날릴게요 ㅎㅎ
