### ISSUE TITLE
$PATH heap-buffer-overflow in get_each_params

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#101]
`$PATH` 환경 변수 입력시 `get_each_params()` 함수에서 heap-buffer-overflow 있습니다... 화이팅!
<img width="985" alt="Screen Shot 2021-09-21 at 4 36 25 PM" src="https://user-images.githubusercontent.com/83805691/134130858-e5949bf9-5fcf-45c8-89f5-2750bda59154.png">
!

**Comment by yongjulejule** [comment]
오 저런 :feelsbadman:

**Comment by yongjulejule** [comment]
머지 이거 고치신거예요?? 왜 그냥 되지?

**Comment by 42ghan** [comment]
?? commit하고 건드리지도 않았는데 ㅋㅋㅋ 대박! 우리 실수로(?) daemon debugging ai를 만들었나봐요 :D

**Comment by 42ghan** [comment]
<img width="1202" alt="Screen Shot 2021-09-21 at 7 04 21 PM" src="https://user-images.githubusercontent.com/83805691/134152243-e6352844-edca-4d1f-b581-95a52660a808.png">
제 맥북에서는 여전히 heap-buffer-overflow 발생하네요... $PATH가 달라서 그런가...

**Comment by yongjulejule** [comment]
그러게요,,, 이상하네 클러스터 가서 테스트 해봐야겠네요.

그리고 환경변수 생각하다 보니 얘도 처리할께 참 많네요

일단 존재하지 않는 환경변수를 입력하면 쉘은 개행만 하고 아무것도 안하구요

$1, $2 ,,,,,, 같은 한자리 숫자는 인자 받아오는 거라서 환경변수가 아니라 안해도 될 듯 하구요(이건 졸림님한테 들은것,,,!)
여기서 파생되는 생각인데, $1ls 이렇게 입력하면 $1이 인자 취급되고 인자가 없으니 그냥 ls로 취급되어서 ls 명령어 결과가 출력되는데 얘까지는 생각하지 않아도 될까? 라는 생각이 드네요

환경변수 문자열 길이 제한도 있지 않을까 싶네요. 대충 구글링 해보니 32000개정도 된다고 하는데 제가 방금 해보니까 40000개 넘는 문자열도 걍 환경변수로 처리합니다. 언제 터지는지 찾고싶은데 흠... 대충 c 코드로 문자열 100만개 정도 출력해서 export $(a.out)=test 이렇게 만들어 보면 되겠네요

참고로 파일명은 255글자, 디렉토리 + 파일명은 1023글자로 기억하는데 좀 가물가물하네요



일단 생각나는데로 다 써놨어요 테스트는 제가 해볼께요

**Comment by yongjulejule** [comment]
_쓰다보니 원래 이슈랑 하나도 관련없는 댓글들이 되었네요 이게뭐람... 나중에 따로 정리해놓겠습니다.._



---

환경변수는 문자 50만개정도까지 받습니다,,, 대체 왜? 대충 구글링해보니 용량으로 제한있는것 같기도 하고,,, 
```sh
bash-3.2$ export $(./a.out 300000)=$(./a.out 300000)
bash-3.2$ echo $(./a.out 300000)
```
네 뭐 이런건 잘먹습니다. 근데 제가 굉장히 흥미로운 사실을 발견했는데,
한 export [50만개 문자열]=[50만개 문자열]
을 하면 선언은 됩니다. 단지
```sh
bash-3.2$ env
bash: /usr/bin/env: Argument list too long
```
이렇게 에러 메시지가 뜹니다. 뭐 각 바이너리가 그에 해당하는 샤뱅이 선언된 채로 만들어지는 프로그램이라 들었는데 
그걸 눈으로 확인할 수 있다는게 너무 신기하고

더 신기한건
<img width="444" alt="Screen Shot 2021-09-21 at 8 39 18 PM" src="https://user-images.githubusercontent.com/79127797/134164086-7fbaff15-16e2-415f-8dbf-107f1165fc30.png">

이렇게 모든 바이너리 명령어가 안먹습니다. bash에서 공용으로 사용하는 메모리라도 있는건지,,,

모든 바이너리가 envp를 인자로 받는걸로 알고 있는데 거기서 터진거같긴 하네요. 갈수록 bash 터트리는 법만 공부하는 느낌😂
사실 터진것도 아니죠. 누가 환경변수로 50만개 문자열을 넣어보겠어,,, 그정도면 undefined behavior 인정이지~~

<img width="412" alt="Screen Shot 2021-09-21 at 8 40 52 PM" src="https://user-images.githubusercontent.com/79127797/134164300-bc05c03b-bc2e-45f1-b787-f57fd47b7b09.png">

또한 builtin cmd들은 실행이 됩니다

---


<img width="1402" alt="Screen Shot 2021-09-21 at 8 16 40 PM" src="https://user-images.githubusercontent.com/79127797/134161458-82b9c0d9-86b0-4005-81e6-c24e506c0d6a.png">


파일명은 상당히 깔끔하네요. 딱 255까지라... 제가 명령어 실행하면서 open할때 체크하는게 좋겠네요. 뭐 알아서 -1 리턴해주면 참 좋겠지만 그런 행복회로따위 돌리진 않겠습니다.

<img width="1426" alt="Screen Shot 2021-09-21 at 8 23 46 PM" src="https://user-images.githubusercontent.com/79127797/134162227-9ceda9bc-5bb2-4ad1-9d74-2bcff6f79917.png">
디렉토리도 깔끔합니다. aa...aa/ <- 이렇게 하나당 255 + 1 (slash까지 256글자) 이고 4번 반복할때까지는 파일이 생성되며 한글자라도 더 있으면  에러가 뜹니다. 딱 1024에서 끊기네요 ㅎㅎ


---

아 러쉬평가 다니면서 평가 및 예외에 진심인분들이랑 이야기하다 보니 이런 생각만 자꾸 하고 있네요 ㅎㅎ 암튼 저런 제한사항이 있다는걸 기록해두고 싶었습니다. 근데 왜 이 이슈에 달고 있는진 모르겠네요. ㅎㅎ 나중에 한번에 정리할께요 봐주세요

**Comment by 42ghan** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 신기하고 재밌네요! $1, $2 이렇게 들어오는게 인자 받는 거였군요... awk에서 그렇게 썼던 기억이 나네요. $ + 숫자 까지는 굳이 안해도 될 것 같네요.

**Comment by yongjulejule** [comment]
와 대박 왜 이생각을 못헀죠? 사실 각 명령어도 argument로 env var을 받는거라서 env var list가ARG_MAX를 넘어가면 에러였던거였어요!
대박신기하다 ㅎㅎ;

<img width="407" alt="Screen Shot 2021-09-22 at 9 22 26 AM" src="https://user-images.githubusercontent.com/79127797/134264432-08e6dfdf-8e6a-40d4-b9d2-f5c71ea95640.png">
환경변수 늘리면서 ARG_MAX 에 가깝게 세팅해보니까 근처에서 터지더라구요

**Comment by 42ghan** [comment]
<img width="536" alt="Screen Shot 2021-09-22 at 9 58 58 AM" src="https://user-images.githubusercontent.com/83805691/134267101-03453751-e845-4ed6-86d8-e9afe3c10920.png">

하핫...숫자 split 고치니까 PATH도 잘 나오네요 ㅎㅎ 다 제 실수 였습니다. 그래도 클러스터에서도 $PATH 한번 테스트 해보죠 혹시라도 파싱 터지는케이스가 있을 수도 있으니까...
그래도 환경변수 관련해서 정리 해놓으신 거 있으니까 이 issue는 열어 둘게요!

**Comment by yongjulejule** [comment]
넹넹 제가 폰으로 보고있어서 ㅎ 다른 내용들은 나중에 옮기고 닫겠습니다

**Comment by yongjulejule** [comment]
$PATH 클러스터에서도 잘됩니다!
