### ISSUE TITLE
Issue : heredoc

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#107]
sigint - 종료 & 파일 삭제

eof - 종료 & limiter가 아니라도 eof까지 읽음, 프롬프트는 출력 -> `>bash-3.2$>` 개행이 없어서 이런 꼴이 됨.
이때 개행 후 처음 문자가eof가 아니면 eof 그냥 무시...! 
미니쉘에서는 gnl때문에 `>` 문자 계속 출력 🤣 쉽게 고칠 수 있음

sigquit - 암것도 안함, core dump도 생성 안함.

**Comment by 42ghan** [comment]
@yongjulejule
아침에 보시겠네요... 굿모닝입니다. 하루의 시작을 esh bug report 와 함께 시작해요! YAY!

heredoc 관련 몇가지 issue 발견해서 남깁니다.

1. cat << (del) - delimiter 오기 전 입력 받는 중에 signal 받으면 무한루프
<img width="478" alt="Screen Shot 2021-09-23 at 1 05 17 AM" src="https://user-images.githubusercontent.com/83805691/134380983-15dddb02-033f-4c80-80ce-22ebf715ccff.png">

2. << (del) SEGV - 아직 안 되는게 맞나요? 이전에는 잘 됐던 거 같은데 예전 버전 코드 받아서 해봐도 터지네요.
<img width="1066" alt="Screen Shot 2021-09-23 at 1 04 26 AM" src="https://user-images.githubusercontent.com/83805691/134381234-3fd88396-ec7c-46dc-9132-7ff05fdc91d5.png">

3. esh heredoc이 히스토리를 못 읽습니다. gnl을 써서 히스토리가 없는데 readline 쓰면서 heredoc 입력 받을 때는 add_history를 안 하는 식으로 하면 bash랑 똑같이 구현되지 않을까 싶네요. bash는 heredoc 입력 중 방향키 위, 아래 누르면 이전 cmds (이전 heredoc 입력 X) history display 됩니다. readline으로 바꾸는게 괜찮으시면 제가 내일 .... 아니 오늘 자고 일어나서 해보겠습니다 ㅋㅋ
<img width="287" alt="Screen Shot 2021-09-23 at 1 06 20 AM" src="https://user-images.githubusercontent.com/83805691/134382298-07d39d4b-32f3-48c2-af8a-4291888d7075.png">

**Comment by yongjulejule** [comment]
3번은 heredoc가 히스토리 업데이트 안해도 된다고 서브직트에 명시되어 있습니다~~ 

1번 시그널은 그전에 처리해뒀었는데 시그널 바꾸면서 상태 이상해진것 같아요. 근데 어떻게 할지 대충 생각나니 제가 고쳐놓겠읍니다.


2번 ??!??!???!???! 뭐지? 원래 잘됐었는데 이거도 해봐야겠네요

**Comment by yongjulejule** [comment]
아 2번 지한님이 strcmp하기 전에 널체크 안해줘서 그렇잖아요~~~

**Comment by yongjulejule** [comment]
pr에 원인 달아놓을께요. 제가 짠 부분이고 구조가 한눈에 안들오니 ㅎㅎ;

**Comment by yongjulejule** [comment]
아 3번 잘못이해했어요 지한님 말씀대로 readline하는게 맞겠네요. 구동도 readline이랑 같구

**Comment by yongjulejule** [comment]
heredoc에서 readline할때 생각나는 주의할점(?)을 정리해보겠습니다.

readline이 입력을 받으며 버퍼에 계속 저장하고 그게 history에 저장되는 방식이 맞죠?
그러면 새로운 readline buffer를 세팅할 수 있나요?

heredoc에서 입력 받으며 쉘의 history를 읽어올 수 있는데, heredoc으로 입력중에 입력한 내용들은 bash에서 history에 업데이트가 안된단 말이죠,, 결국 버퍼가 분리되어야 한다는 생각이 드는데, 혹은 heredoc중에 입력받은 내용은 버퍼에서 지운다거나, 이게 가능하겠죠/?

가능하다면 readline을 하면서 내용을 파일에 쓸 수 도 있고, 굳이 파일에 안쓰고 heredoc에 해당하는 버퍼만 가지고도 구현할 수 있겠네요.
제발 됐으면 좋겠네요. 

gnl로 할때 문제점이 history 뿐만 아니라 
입력이 있다가 개행하지 않고 eof->완전히 무시! 
개행 후 바로 eof -> 입력 종료
이렇게 되는데, 개행하지 않고 eof가 나오면 gnl이 line을 가져오게 되고, 그 line에 다시 strjoin을 해서 line을 업데이트 해야 하는데 이게 참 쉽지않단 말이죠,,,

**Comment by 42ghan** [comment]
ㅋㅋㅋㅋ strcmp NULL 체크 ㅋㅋㅋㅋㅋ 아니.. libft 는 다 null guard 해준다고 생각했는데 다시 생각해보니 아니네요 ㅋㅋㅋㅋㅋ 어째 해결하는 issue 보다 제가 만드는 issue가 더 많은 듯 (머쓱)

readline 사용하면
- eof 문제는 해결 됩니다.
- history 업데이트 분리는 가능할 걸로 보입니다.
- readline 하면서 내용을 파일에 쓰는 것도 가능할 것 같아요 아마도

보내주신 PR로 1번 문제는 해결 됐는데 shell on shell 이 다시 이상해졌네요. 그리고 heredoc 중에 SIGQUIT 보내면 불필요한 개행이 됩니다. << signal 문제하고 readline 부분 터미널이랑 시그널 관련이니까 제가 고쳐볼게요. 나중에 확인해주세요. 용줄레님은 builtin 해주세요 :)

**Comment by yongjulejule** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 일단 알겠습니당

**Comment by 42ghan** [comment]
heredoc 새로운 issue 발견... bash에서는 pipe에 heredoc 해도 잘 되는데 esh은 좀 이상해지네요...하

bash:
<img width="573" alt="Screen Shot 2021-09-23 at 2 14 21 PM" src="https://user-images.githubusercontent.com/83805691/134458000-d9431085-9695-4d8f-9580-1415f41c7917.png">

esh (입력값이 terminal에 출력 안 되는걸 보니 fd가 좀 꼬이는 것 같네요..ㅠㅠ):
<img width="402" alt="Screen Shot 2021-09-23 at 2 14 48 PM" src="https://user-images.githubusercontent.com/83805691/134458034-73da7cf7-b915-4081-821a-fe55a7498d69.png">
<img width="764" alt="Screen Shot 2021-09-23 at 2 19 48 PM" src="https://user-images.githubusercontent.com/83805691/134458088-ffa91e29-dd7d-4d8b-81dc-612de0fb394a.png">

**Comment by yongjulejule** [comment]
아니 이거 뭐죠 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ readline 때문인가...? 아악!
