### ISSUE TITLE
Issue : builtin in pipe

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#111]
파이프라인에서 builtin을 실행하면 아무것도 안하는것 처럼 보이지만 뭔가 합니다,,

하지만 환경변수 세팅같은건 안되더라구요?
<img width="955" alt="Screen Shot 2021-09-23 at 10 22 54 AM" src="https://user-images.githubusercontent.com/79127797/134442220-5faf9910-3c4d-47a5-8290-c50e086d0d11.png">

확실히 실행되는게 보이긴 합니다.
<img width="978" alt="Screen Shot 2021-09-23 at 10 24 38 AM" src="https://user-images.githubusercontent.com/79127797/134442321-9f100f3b-f50b-4922-b4d9-cf0b7e28003e.png">

exit 같은건 실행되고
<img width="943" alt="Screen Shot 2021-09-23 at 10 23 37 AM" src="https://user-images.githubusercontent.com/79127797/134442260-f89ab5ff-7044-433b-bb34-963b18b4f6c2.png">

물론 exit status는 마지막 커멘드에 따라 나오니 중간에 있으면 의미가 없긴 합니다
<img width="934" alt="Screen Shot 2021-09-23 at 10 23 57 AM" src="https://user-images.githubusercontent.com/79127797/134442280-8c337f72-4701-4636-8f91-140e3f01edb6.png">

파이프라인의 구동방식을 생각해보면, 각각 자식프로세스를 생성하여 명령어를 실행하는 방식인데, 그 자식프로세스에서 환경변수같은거 업데이트 해도 다른 자식프로세스에는 영향을 미칠 수 없으니 `export, unset` 같은건 안먹는걸로 보입니다.

결국 execve와 같은 방식으로 구동되게 만들면 되겠다 싶었지만, 환경변수 세팅 / 삭제하는 아이들은 마지막에 exit를 하면 안되며
파이프로 넘어갔을땐 exit가 되어야 합니다

으으.. 그럼 젤 머리아파보이는 export, unset 먼저 짜보겠습니다

**Comment by yongjulejule** [comment]
아니 환경변수 개어려워요 ㅡㅡ 다른거 부터 짜겠습니다.

일단 정리 해놓고 넘어갈께요,,
프로그램 실행시 데이터영역에 전역변수 environ이라는 아이가 있어 얘네로부터 환경변수들을 가져오고 수정합니다.
getenv, setenv 등등 함수는 저 environ을 사용하죠

main에서 envp로 환경변수 받아올 수 있는 원리는 그저 envp가 environ의 주소를 똑같이 가져오기 때문입니다. 따라서 envp의 주소가 바뀌면 envp로 전역변수에 접근을 못합니다. 새로운 주소에 문자열을 넣어줘도 getenv같은 아이로 특정 환경변수를 가져오지는 못합니다.

execve할 때 환경변수 리스트의 주소를 넘겨주면 되기는 하니 그냥 새로운 envp 리스트를 만들어서 거기에 환경변수를 삭제 / 추가 하면 되긴 하지만 getenv 함수로 환경변수를 받아오기는 어려워 보입니다.

environ에 직접 업데이트를 시키려면 저게 데이터 영역이니 컴파일단계에서 크기가 정해져서 오는데, environ의 주소가 가리키는 메모리의 크기를 조절하는 방법은 realloc 밖에 안떠오르네요. 그 마저도 주소가 변경될 가능성이 있는걸로 압니다
<img width="610" alt="Screen Shot 2021-09-23 at 11 11 45 AM" src="https://user-images.githubusercontent.com/79127797/134445312-7bb95845-18b6-4501-97cf-253db3ba4a94.png">

뭐 그래도 환경변수는 30개밖에 없는데 232번 정도까지 여유공간이 있긴 하네요.


더 테스트를 해보니까 환경변수 700개정도 세팅될때부터 bash는 환경변수를 더이상 세팅 못하고 argument가 너무 많다고 아무런 커멘드도 안먹는데

c언어에서 setenv를 통해서는 몇천개까지 세팅할 수 있네요

근데 이 세팅하는 원리가 environ에 업데이트 하는게 아니고 별도의 배열에 업데이트 하는 방식 같네요? getenv도 거기서 받아오고
근데 ㅈ ㅓ함수들을 일일이 뜯어볼 수 없으니 결국

메인에서 envp 받은걸 그대로 다른 배열에 복사하고 그 배열을 저희 쉘 내 전체에서 envp들로 핸들링하며 getenv는 못쓰게될것 같은데
어떻게 할지 모르겠네요 ㅎㅎ 왜케 어렵죠

다른거부터 만들으러 갑니다~~

```c
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>

int main(int ac, char **av, char **envp)
{
	int idx;
	char tmp[10000];
	extern char **environ;
	char **test;

	test = environ;


	idx = 0;
	memset(tmp, 0, 9999);
	while (idx < 2000)
	{
		tmp[idx] = 'a';
		printf("%d\n", idx);
		if (-1 ==setenv(tmp, &tmp[idx], 0))
		{
			perror("");
			break;
		}
		if (idx == 1000)
		{
			printf("%p, %s\n", environ[999], getenv(tmp));
			while(1);
		}
//		printf("export");
//		printf(" %s=", tmp);
//		printf("%d\n", idx);
		idx++;
	}
}
```

혹시나 해서 올려둡니다~~ 주석부분을 지우고 $(./a.out)을 하면 쉘에 환경변수가 등록되는걸 확인할 수 있어요~~~~ 물론 bash 실행해서 하시는거 추천드립니다 ㅎㅎ 아니면 그 쉘 껐다켜야해요

**Comment by 42ghan** [comment]
으으... 진짜 쉬운게 없네요... 미니쉘 개꿀잼 하하하하하하
