### ISSUE TITLE
Issue : heap-buffer-overflow & SEGV for complex command

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#115]
cat 123241<&->stopminishell wow crazy | ls | wc > "please \n stop"
위 커맨드 입력시 터집니다... 왠지는 모르겠네요.

make 시 SEGV, make debug 시 heap-buffer-overflow
<img width="1123" alt="Screen Shot 2021-09-23 at 2 12 42 PM" src="https://user-images.githubusercontent.com/83805691/134457517-e613909b-78d3-41c4-8e44-f6ca75c0969a.png">

**Comment by yongjulejule** [comment]
<img width="785" alt="Screen Shot 2021-09-23 at 3 06 07 PM" src="https://user-images.githubusercontent.com/79127797/134461171-f1bb89de-fd40-44ef-96a5-0f36fd5433d7.png">

`-` 뒤에 오는 리다이렉션 기호는 분리되어야 합니다 ㅠㅠ `<&-> == [fd]<&- [stdout]>[file]`  == fd를 닫고 , stdout는 리다이렉션 해라

저 명령어를 해석해보자면
cat 을 하는데 123241번 파일디스크립터는 닫고(여기서 에러가 나야 한다고 생각하지만 배쉬도 안나네요?) 
(여기까지가 cat 123241<&-)
cat 한 stdout을 stopminishell에 쓰는데 (>stopminishell == stdout을 파일에 써라)
이때 cat이 읽는건 wow, crazy란 파일임(저 파일들이 있으면 cat해서 stopminishell에 써짐)

그리고 파이프따라 ls로 넘어갑니다. 물론 stdout가 리다이렉션 됐으니 의미없는 파이프긴 하죠

**Comment by yongjulejule** [comment]
아 그리고 `<&[fd]-` 이 케이스도 파싱 하셨다고 했죠? 까먹고 안하고 있었네 ㅎㅎ; 해놓겠습니다~~~

**Comment by 42ghan** [comment]
아하 #67 기준으로 해놨었는데 - 뒤에 오는 기호가 분리되야 하는군요. 수정하겠습니다. `<&[fd]-` 해도 되고 안해도 됩니다. 저도 어쩌다 보니 그냥 파싱이 됐던 거라 ㅋㅋ 그냥 터지지만 않으면 될 것 같아요. 빌트인 하신 다음에 하고 싶으시면(?) 하세요 ㅋㅋㅋㅋ

**Comment by yongjulejule** [comment]
으악 제가 저렇게 써놨었네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 잘못된겁니다,,, :fakenews: 빌트인 하다 생각해보겠습니당

**Comment by yongjulejule** [comment]
원인은 wow를 커멘드로 인식해서 카운트가 꼬여서 그렇읍니다... 고쳐보겠습니당

**Comment by yongjulejule** [comment]
후후... 한 커멘드 내에서 커맨드 + 리다이렉션 + 다른 옵션들 이 오면 터지네요! 히히힣신난다꺄핳하미니쉘재밌어꺆ㄲ
