### ISSUE TITLE
Issue : cmds data structure

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#117]
지한지한님 커멘드 파싱하실때 리스트 쓰셨다고 하셨죠???
그러면 
`ls >a >b <>c d | f g;`
이렇게 커멘드가 들어오면
`ls` -> `>a` -> `>b` -> `<>c` -> `d` -> `|` -> `f g` -> `;`

이렇게 리스트 만드셨나요? 아마 그렇겠죠?
저 리스트를 그대로 넘겨주실 수 있나요?? 

제 부분에서 다시 리스트로 바꾸고 파싱해도 되긴 하는데 만약 저런 형태면 똑같은 구조를 왔다갔다 하게 되어서 이게 뭐하는건가 싶어서요 ㅎㅎ;

구조를 최대한 유지하면서 segfault를 고치려 했는데 코드가 상상 이상으로 더러워지더라구요 히히힣 신난다

**Comment by yongjulejule** [comment]
만약 저런 형태가 아니라면 알려주세요. 제가 바꿔서 사용해도 됩니다. 차피 `libft`에서 만든 리스트 갖다쓰면 되어서 얼마 안걸려요

**Comment by 42ghan** [comment]
네 리스트 저렇게 만들었는데 리스트로 보내드릴게요. 제 리스트가 

(head)->(elem)->...->(elem)->NULL이니까 head를 넘겨드릴게요. 지금 처리해서 pr 보낼게요.

**Comment by yongjulejule** [comment]
굿굿 감사합니다~~~

그리고 제가 파이프엑스에서 썼던 함수들 당연히 여기서도 쓸 수 있겠지 싶다가 아닌거 발견했어요~~~ 미친인간 아녜요 이거? ㅎㅎ; 
`access` 함수를 썼었는데 `open`으로 대체 가능하지만 `stat` 함수를 활용해볼 생각입니다~~~ 네 tmi였구요 감사합니다 [z플립 제리짤]
