### ISSUE TITLE
Issue : internal prompt SIGINT handle MACRO function

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#120]
![Screen Shot 2021-09-24 at 3 39 21 PM](https://user-images.githubusercontent.com/83805691/134629696-c1c63c66-a823-4bcf-9695-03c982938060.png)

quotation mark, backtick 이나 pipe가 안 닫혀서 열리는 internal prompt SIGINT로 닫을 때 ioctl 함수를 쓰는데. 이때 fake input을 STDIN에 넣어줄 때 쓰는 `TIOCSTI` 매크로가 매크로 함수였네요... 자체 구현 도전 해보겠습니다..

**Comment by yongjulejule** [comment]
_No description provided._
