### ISSUE TITLE
Issue : changing env value without export

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#132]
export cmd 를 쓰지 않아도 이미 환경변수가 존재한다면 shell command line에 (환경변수)=(새로운 값)을 넣으면 새로운 값으로 환경변수 값이 바뀌네요. 이 부분도 구현해야할까요?
![Screen Shot 2021-09-26 at 4 45 22 PM](https://user-images.githubusercontent.com/83805691/134798705-0e36926b-80de-46d9-bf82-81d165cf7399.png)

**Comment by yongjulejule** [comment]
export를 구현하라고 했으니까 안해도 되지 않을까요? ㅎㅎ
