### ISSUE TITLE
Issue : leaks in parsing

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#134]
지한님 파트 릭 이렇게 납니당 cmd 배열(?) 릭이 생기네요?

lldb 돌리면서 릭 보는데 파싱 직후 화면입니당

<img width="716" alt="Screen Shot 2021-09-26 at 5 01 17 PM" src="https://user-images.githubusercontent.com/79127797/134799167-03c65470-2816-49c0-b88c-886baa7a1311.png">
asd asd >a >b >c aa<asd sdf<>Afa ;asf aas 이렇게 입력했을 때 입니다

**Comment by 42ghan** [comment]
오호..감사합니다...
