### ISSUE TITLE
Issue : cmd exec parsing error

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#139]
![Screen Shot 2021-09-26 at 6 12 51 PM](https://user-images.githubusercontent.com/83805691/134801657-6859734a-6d27-4676-b2bc-e47eb6b3b942.png
![Screen Shot 2021-09-26 at 6 21 13 PM](https://user-images.githubusercontent.com/83805691/134801696-93bdd8bd-2980-4a4b-bcce-29b936f834d5.png)
)

위 케이스에서 backslash를 skip 하지 않고 \를 의미있는 문자로 인식하네요.

**Comment by yongjulejule** [comment]
잉 아 저 여태 백슬레쉬 하나도 고려 안하고 짰는뎈ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 망했다!

**Comment by 42ghan** [comment]
@yongjulejule 
음... 뒤에서 \이 따로 필요하신게 아니면 \ 없애는 작업을 parsing 쪽에서 할까요? 아직 시작 안하셨으면 제가 해도 될 것 같아요.

**Comment by yongjulejule** [comment]
그런 기가막힌 아이디어를 생각해내시다니 지한님 혹시 천재???!???! 그러면 좋습니당 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by 42ghan** [comment]
아니 생각해보니 \ 필요 없으실 것 같아서 ㅋㅋ
