### ISSUE TITLE
Issue : interpret double-quote in double-quote

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#144]
bash는 `"` 안에 `"`도 문자로 취급하긴 하는거 같습니다. 아니면 `{` 가 나오면 닫혀야 한다거나. 후자가 더 설득력 있겠네요.
단지 이유는 모르겠지만 아래 커맨드를 입력하면 입력을 한번 에러를 뱉습니다
<img width="577" alt="Screen Shot 2021-09-27 at 7 58 59 PM" src="https://user-images.githubusercontent.com/79127797/134895976-47980803-47d0-437f-83e0-db9c15206135.png">

저희 minishell은 `"` 안에 `"`가 오면 당연히 quote가 닫힌걸로 인식하여 커멘드가 끊깁니다.
저희같은 경우는 입력을 받지 않고 바로 에러를 뱉습니다.
<img width="497" alt="Screen Shot 2021-09-27 at 7 59 17 PM" src="https://user-images.githubusercontent.com/79127797/134896019-d2989a97-baff-472d-8930-30b82c7e51c2.png">

저희는 미니쉘 서브젝트에 나온 대로 엄격하게 파싱한거니 배쉬가 틀린겁니다.

참고로 원래 저 커맨드는 quote를 구분해줘야 작동합니다. 이건 저희 미니쉘도 잘 작동해요. 굳
<img width="555" alt="Screen Shot 2021-09-27 at 8 02 26 PM" src="https://user-images.githubusercontent.com/79127797/134896430-deb7a753-bbc0-4e1c-9977-966805091541.png">

이런식으로 quote를 해석하지 마라고 주면 bash도 minishell도 잘 작동합니다.
<img width="544" alt="Screen Shot 2021-09-27 at 8 03 22 PM" src="https://user-images.githubusercontent.com/79127797/134896551-acbcb3aa-af29-4c8e-971e-50648686fa79.png">

아마 배쉬는 {, } 같은 괄호 기준으로도 파싱하지 싶은데 저희 미니쉘은 그렇지 않으니 알아두시면 좋을것 같습니다~~~

**Comment by 42ghan** [comment]
아 다행이네요... 알림 뜬 거 보고 내심 걱정했는데 ㅋㅋㅋ 원하는 결론을 내려주셔서 감사합니다!
