### ISSUE TITLE
Issue : Honey tips in github

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#145]
코딩 아이돌님께 많은 이야기를 들었습니다,,,

일단 아이돌님께서는 파싱할때 AST 쓰셨고 비트플래그를 대박잘활용하셨는데 이건 궁금하시면 직접 설명 드릴께요. 한 10%는 설명할 수 있을듯. 코드 대박멋있어요

[god-jaeskim's tip](https://github.com/gachi-mandoo-shell/kimchi-mandoo-shell/tree/master/.github/workflows)
그리고 PR에 github action을 연결할 수 있어서 merge를 거부할 수 있다고 합니다. norm과 make를 해서 에러가 있으면 머지가 안되는 식으로 말이죠.

저게 어떤 원리로 되냐 했더니 stderr로 나오는것, 리턴이 0이 아닌것이 있으면 그것을 토대로 판단한다고 하더라구요? 진짜 대박신기해요 대박대박 stderr 스트림을 그렇게 활용하다니 너무 신기해요 진짜 ㄴㅇ0ㅇㄱ

거의 마무리 단계지만 함 적용해볼까요? 재밌을것 같네요

**Comment by 42ghan** [comment]
오 코딩 아이돌 재스킴님... 궁금하네요 AST. 알 거 같으면서도 어떻게 활용하는 건지 감이 안 잡혔는데... 깃헙 액션 목요일부터 써보죠 ㅋㅋㅋ 아직 built-in 쪽이 unused variable 때문에 make 안 되는 상황이라서 ㅋㅋㅋ
