### ISSUE TITLE
Issue : read line too much

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#146]
그리고 슬픈 소식이지만 진짜 버그입니다
<img width="317" alt="Screen Shot 2021-09-27 at 9 03 39 PM" src="https://user-images.githubusercontent.com/79127797/134904582-f9ec5eb0-1337-434c-8333-1f5c217b221f.png">

입력이 끝나야 할텐데 계속 받습니다.

그리고 더 충격적인 소식이 있습니다.
backslash 안해도 된다네요. 그전 미니쉘에선 해야헀지만,,,
이게뭐람!!!!!!!

뭐 저희 안해도 되는데 한거 대박 많으니 그러려니 하지만 왜 미니쉘이 쉬워졌다고 하는지는 알겠네요. 으어어러어ㅏ ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by 42ghan** [comment]
오 저런 ... 고치겠습니다 ㅋㅋㅋㅋ bslash도 안 해도 되는 거였다니... 정말 esh에게는 minishell이라는 이름이 안 어울리는군요 ㅋㅋㅋㅋ 작고 귀여운 medium shell, esh 🐘
