### ISSUE TITLE
Issue : bash does not interpret consecutive quotes

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#149]
<img width="544" alt="Screen Shot 2021-09-28 at 11 16 35 AM" src="https://user-images.githubusercontent.com/79127797/135011488-d5208015-31d3-4758-a5e8-4ceddaf98771.png">

but minishell interpret it 🤪

**Comment by 42ghan** [comment]
아... 이건 고쳐야겠네요...ㅠㅠㅠ 접수 했습니다!

**Comment by yongjulejule** [comment]
![HAHAHA](https://emoji.slack-edge.com/T039P7U66/feelsbadman/c9d62bf6feddb4cf.png)

**Comment by 42ghan** [comment]
단지 연속적인 quote이 들어올 때의 문제가 아니네요.

quote 앞/뒤로 whitespace가 없으면 quote이 무시되네요. (물론 quote은 닫혀야합니다.)
![Screen Shot 2021-09-28 at 3 37 08 PM](https://user-images.githubusercontent.com/83805691/135035882-3f54d45f-8e8e-45b4-8dca-5b5a8fca7174.png)
![Screen Shot 2021-09-28 at 3 37 24 PM](https://user-images.githubusercontent.com/83805691/135035708-216bf7eb-740e-43f5-b111-908bcd10de53.png)

더 가관인건 quote 앞/뒤로 whitespace가 없는데 quote이 닫히지 않아서 internal prompt가 열리면 `enter` key 누르는게 개행으로 인식된다는 점입니다.
![Screen Shot 2021-09-28 at 3 40 11 PM](https://user-images.githubusercontent.com/83805691/135036024-329362ff-0d9e-4eed-9f8c-be16e4cd62d2.png)

너무 즐거워서 웃음이 떠나질 않습니다 🙃 
시간이 좀 걸릴 수 있습니다 🙃

**Comment by 42ghan** [comment]
아 internal prompt에서는 quote 앞/뒤로 whitespace가 있든 없든 `enter` key 들어오면 `\n`으로 인식하네요 🙃

**Comment by yongjulejule** [comment]
아 맞아요 quote 내에선 엔터도 그냥 문자취급 해버려요:feelsbadman: 어우 지한님이 넣어보신 값 보니까 대박끔찍하네요 으아아앍
