### ISSUE TITLE
Issue : $_ is mysterious

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#154]
`$_` 이 녀석 좀 이상한 녀석이네요.

어제 테스트 할때는 마지막 word를 인식한다고 생각했는데 꼭 그렇진 않습니다.
gnu bash 문서를 보니
<img width="768" alt="Screen Shot 2021-09-28 at 3 55 59 PM" src="https://user-images.githubusercontent.com/83805691/135038196-6afbb81e-ff76-48ab-afda-964b8e0e2f1b.png">

## **1. shell이 시작할 때 shell path name으로 설정됩니다.**

![Screen Shot 2021-09-28 at 3 58 08 PM](https://user-images.githubusercontent.com/83805691/135038523-dcc5ad8a-6f53-468b-9e27-d2add462842d.png)

shell 시작한 직후가 아니면 `export`(인자 없이) command로는 `_`의 value를 볼 수 없습니다...

## **2. 그 후로는 마지막 인자/단어로 설정 되는게 맞습니다.**

![Screen Shot 2021-09-28 at 4 08 29 PM](https://user-images.githubusercontent.com/83805691/135039795-933b158f-0e38-4502-b7cf-e7b7b875242d.png)

하지만 이게 전부가 아닙니다...

## **3. 실행 파일 실행시 실행 파일의 path로 설정되기도 합니다.**

![Screen Shot 2021-09-28 at 4 10 06 PM](https://user-images.githubusercontent.com/83805691/135040007-4be71926-496c-4273-a658-d85f6cb4cd07.png)

재밌는 건 명령이 실행될 때마다 `$_`가 업데이트 되기 때문에 이 경우는 `printenv`/`env`가 아니면 확인할 수 없습니다 (적어도 제가 알기론)...

+) 마지막으로 이 녀석이 아주 재밌는 이유가 하나 더 있습니다.
![Screen Shot 2021-09-28 at 4 10 06 PM](https://user-images.githubusercontent.com/83805691/135040688-5c550399-f8b4-4821-97b6-2faa909610c6.png)

`export`가 성공할 때는 마지막 인자에서 "=..."은 무시합니다. 다른 경우는 '='와 그 뒤에 나오는 문자들도 받습니다.

너무 즐겁습니다 🙃

**Comment by yongjulejule** [comment]
아니 저게뭐람 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 괜히 환경변수가 어렵다 하는게 아니였군요 화이팅 ㅎㅎ,,,,,
