### ISSUE TITLE
Issue : error in cmd parsing for exec

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#160]
아래 두 경우 `exec_cmd_main()` 전 파싱은 제대로 됐는데 이후에 exec 전에 2차 파싱 하는 부분에서 문제가 생기는 것 같습니다.

1. internal prompt 열리면서 `\n` 두번 입력되고 이 개행들은 trim 되면 안 됩니다.
![Screen Shot 2021-09-29 at 6 38 32 PM](https://user-images.githubusercontent.com/83805691/135244033-72eaa522-64be-4b51-a0a0-3fc6177865ed.png)

2. a 가 사라집니다!
![Screen Shot 2021-09-29 at 6 38 39 PM](https://user-images.githubusercontent.com/83805691/135243801-7cbf1789-5f5f-44f8-9d89-5187898c2d60.png)

-------- 절취선 안에 있는 출력값이 파싱 직후 `exec_cmd_main()` 들어가기 전 출력된 겁니다.

**Comment by yongjulejule** [comment]
그 지한님 1번사항에 저희
> \>"
> \>ls
> \>"

이렇게 오면
>"\nls\n"

이렇게 따옴표가 유지된 채 제 부분으로 넘어오는거 아니였나여??

**Comment by 42ghan** [comment]
아 그렇네요 버그 맞습니다... 제가 qm 없애면서 너무 많이 없앤 것 같네요... 지금 가는 길입니다 ㅋㅋ 가서 고칠게요!

**Comment by yongjulejule** [comment]
얍얍 알겠습니다~~
