### ISSUE TITLE
Issue : heredoc #158

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#161]
#158 이슈로 남겨놓는게 좋을것 같아 남겨둡니다,,,

저런식으로 리다이렉션이 가능하면 정말 쉽게 해결 가능해 보이네요~!~!

내일 해보면 될듯 싶습니다. 이미 나와버려서 더이상 코드를 짤 수 없어요(단호)

**Comment by 42ghan** [comment]
넵 ㅋㅋㅋㅋ 푹 쉬시고 내일 봬요~
