### ISSUE TITLE
Issue : Crash! 💥

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#162]
<img width="1419" alt="Screen Shot 2021-09-30 at 9 25 22 AM" src="https://user-images.githubusercontent.com/79127797/135366189-2dd07ea1-6c5d-4a6e-870e-a6630dcdc900.png">

ㅎㅎ 무한루프에 빠진거 같아요.
한명이 버그 리포트해서 고치려고 테스트 케이스 넣어보면 다른쪽도 터지고
그거 고치려고 테케 넣으면 또 반대편에서 터지고

하하! 즐겁다!

**Comment by 42ghan** [comment]
아 개꿀잼... 좀 쉬고 계세요 ㅋㅋ

**Comment by yongjulejule** [comment]
아녀 저도 ls "a" 고쳐야해요~~~ ls "\\\"" 이걸 처리하면 "a"가 사라지고 "a"를 부활시키면 "\\\""가 문제 생기는 상황이네요 하하하하하 신난다

**Comment by 42ghan** [comment]
Union식으로 파싱 한다고 하죠 뭐

**Comment by yongjulejule** [comment]
<img width="1858" alt="Screen Shot 2021-09-30 at 9 56 30 AM" src="https://user-images.githubusercontent.com/79127797/135368406-46cdfad6-8898-4333-8246-f0455c182679.png">

하하! 그래도 저흐 ㅣ열심히히 했어요

<img width="1876" alt="Screen Shot 2021-09-30 at 9 59 10 AM" src="https://user-images.githubusercontent.com/79127797/135368511-5d4aff7b-afc8-44b8-8306-8fd019c79acd.png">

라고 말하려고 막 타이핑 해봤는데 왜 마지막부분이 달라질까요? 히힣 신난다 띄어쓰기 있어서 인자로 인식해야 하는데 인식을 안하네 하하핳
