### ISSUE TITLE
issue : env does not expend if it does not setted

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#170]
<img width="613" alt="Screen Shot 2021-10-01 at 10 36 52 AM" src="https://user-images.githubusercontent.com/79127797/135552348-15ff73cf-f4aa-4dd2-a717-423b0ffc1839.png">

이거 원래 이랬던가요??? 원래 됐던것 같은디

**Comment by 42ghan** [comment]
아 저거는 원래 저런데...bash를 보니 없는 변수면 그냥 '/0'이 들어가나 보네요. 수정하겠습니다~

**Comment by yongjulejule** [comment]
알겠습니다~~~

하하! ""가 삭제되면서 배쉬랑 달라진게 또생겼네요 하하!!!! 신난다!!!!와!!!
<img width="589" alt="Screen Shot 2021-10-01 at 10 41 55 AM" src="https://user-images.githubusercontent.com/79127797/135552692-7e5e7895-cbec-49a8-8b59-510a3088bb7e.png">

**Comment by 42ghan** [comment]
bash에서 `ls >""` 했을 때 syntax error 안 뜨나요? 지금 밖이라 제가 테스트 할 수가 없네요

**Comment by yongjulejule** [comment]
넹 파일이 없다고 뜹니다. "\0"란 파일에 쓰려고 하는거 같아욤

**Comment by 42ghan** [comment]
아하.. 어디서 뭘 고쳐야하는지는 알겠네요 ㅋㅋ 감사합니다
