### ISSUE TITLE
Issue : echo arg with whitespace

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#172]
![Screen Shot 2021-10-01 at 2 01 13 PM](https://user-images.githubusercontent.com/83805691/135567822-54ba701b-353d-43b6-b52b-922328bcbb8b.png)

`echo`의 경우 whitespace가 있어도 하나의 인자로 인식하는 것 같네요.. 처리하겠습니다 :)

**Comment by yongjulejule** [comment]
<img width="321" alt="Screen Shot 2021-10-01 at 2 05 04 PM" src="https://user-images.githubusercontent.com/79127797/135568072-f16476e9-5e1d-4e03-9f65-2d9d2c54f2c8.png">

맞아 에코 좀 ㅁ이상한 특성 있어요

그냥 각 인자로 보고 출력하는데 인자마다 공백을 하나씩 주는듯...?싶네요

**Comment by 42ghan** [comment]
아하 공백을 하나씩 주는군요 알겠습니다!
