### ISSUE TITLE
Issue : minishell-tester

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#174]
https://github.com/solaldunckel/minishell-tester

작동하는 테스터 찾았읍니다,,, 일케 만들면 되는군요

단지 프롬프트와 아스키아트를 stderr로 출력하라 그래서 다 틀렸다고 뜨긴 합니다 (이건 맞춰주는게 맞는듯)

대충 보니까 echo빼고는 맞는거 같네요

그리고 어느 시점부터 테스터가 안도는데 원인은 함 찾아보겠습니다

**Comment by 42ghan** [comment]
오 대박! 저는 지금 `$_` 너무 노답이어서 _world_general에 꼭 해야하는 건지 물어보려고요 ㅋㅋㅋㅋ

**Comment by 42ghan** [comment]
echo는 고쳐놨습니다. 곧 pr 보낼게요

**Comment by yongjulejule** [comment]
<img width="1039" alt="Screen Shot 2021-10-01 at 3 54 07 PM" src="https://user-images.githubusercontent.com/79127797/135578159-d084ff2e-b97c-4768-a6c0-0b6725c03feb.png">

원인을 찾ㅇ았읍니다... 좀 슬픈 원인이네요

**Comment by 42ghan** [comment]
오께이... 좀 울고 올게요...ㅋㅋㅋㅋㅋㅋㅋ

**Comment by yongjulejule** [comment]
<img width="1199" alt="Screen Shot 2021-10-01 at 4 03 09 PM" src="https://user-images.githubusercontent.com/79127797/135579105-18af78cc-e49d-425c-979f-03d358a1057b.png">
또 발각하였습니다. 

`export TEST ; export` 까지는 잘 작동하는데 `export TEST; export | sort` 이렇게 파이프 오고 나서부터 터지네요. 이 부분은 제 잘못일 수도 있겠어요

**Comment by yongjulejule** [comment]
<img width="608" alt="Screen Shot 2021-10-01 at 4 25 01 PM" src="https://user-images.githubusercontent.com/79127797/135581708-1404094b-a536-4e6a-940a-55843bb6f7eb.png">

와우 exit 인자를 안주면 에러코드를 유지시키는거였네요? ㄴㅇㄱ

**Comment by yongjulejule** [comment]
readline 프롬프트를 stderr로 바꾸고 싶은데 readline 실행 전에 rl_outstream->_file 을 접근하면 터지더라구요? readline함수를 시작하면서 저 구조체가 생기는것으로 보여서 readline 밑에서 rl_outstream을 바꿔주니 한번 stdout으로 프롬프트가 출력되고 그 다음부터 stderr로 출력됩니다,,, 몹시 당연한 소리 이지만 이를 어케 해결하는게 좋을까요?

**Comment by yongjulejule** [comment]
<img width="976" alt="Screen Shot 2021-10-01 at 4 40 36 PM" src="https://user-images.githubusercontent.com/79127797/135583509-dd0bc983-22c1-45a6-996e-893f71377ac6.png">

echo 수정하고 터지는 문제 같읍니다. 그 전엔 안떴거든요.(물론 출력값이 달랐을수도 있었지만 터지진 않았습니다)

**Comment by 42ghan** [comment]
아 저런... 차분히 하나씩 고쳐볼게요 ㅋㅋㅋ

**Comment by 42ghan** [comment]
> <img alt="Screen Shot 2021-10-01 at 4 03 09 PM" width="1199" src="https://user-images.githubusercontent.com/79127797/135579105-18af78cc-e49d-425c-979f-03d358a1057b.png">
> 
> 또 발각하였습니다.
> `export TEST ; export` 까지는 잘 작동하는데 `export TEST; export | sort` 이렇게 파이프 오고 나서부터 터지네요. 이 부분은 제 잘못일 수도 있겠어요

export가 pipe로 들어갈 때만 터지네요... 저도 이유 찾아볼게요

**Comment by 42ghan** [comment]
> readline 프롬프트를 stderr로 바꾸고 싶은데 readline 실행 전에 rl_outstream->_file 을 접근하면 터지더라구요? readline함수를 시작하면서 저 구조체가 생기는것으로 보여서 readline 밑에서 rl_outstream을 바꿔주니 한번 stdout으로 프롬프트가 출력되고 그 다음부터 stderr로 출력됩니다,,, 몹시 당연한 소리 이지만 이를 어케 해결하는게 좋을까요?

맞아요 이거 난감하죠...ㅋㅋㅋㅋ 저도 고민해보겠습니다

**Comment by yongjulejule** [comment]
rl_outstream을 바꾸니 테스터가 좀 보기 편-안해졌군요.
터진거 찾기 더 쉬워졌다 이말입니다.

일단, `echo -n -n -n abc` 이런 경우 `-n`들을 다 옵션취급해서 출력 안하더라구요. 이건 쉽게 고칠 수 있을거 같아서 고쳐뒀습니다.

`mkdir test_dir; cd test_dir; rm -rf ../test_dir; cd .; pwd;`
테스트 케이스에 이거☝️ 비슷한 케이스가 있는데
`rm -rf ../test_dir` 까지는 잘 되고 `cd .` 하면 현재 디렉토리에 가만히 있는데 PWD는 날아가버립니다.

cd 코드 짜신걸 유심히 살펴보니 getcwd의 예외케이스로 터지는듯 하네요. 
가설을 검증하기 위해 테스트 케이스를 살짝 확장해봤습니다.
<img width="418" alt="Screen Shot 2021-10-02 at 2 48 51 PM" src="https://user-images.githubusercontent.com/79127797/135705243-67c89375-12e8-4dc4-b281-284828ee3be0.png">

맞는듯 싶네요. getcwd man page를 보니 얘도 실패시 errno 반환하는거 보아 예외처리 필요할 것 같고, . 이나 ..같은거 할 시 PWD는 다른 방법으로 세팅해줘야 할 듯 싶습니다.

근데 얘를 요리조리 극한의 케이스까지 확장하면... 예를들어 `rm ../../../../../../../../dir; cd ../.. ; pwd;` 이런게 있으면 참 머리아파지지 싶네요.
갑자기 생각난건데 minishell subject에 cd 는 절대경로나 상대경로 둘중 하나로 구현하면 된다고 나와있던게 떠올랐읍니다. 둘 다 쉽지 않나? 생각했던 본인을 반성하며 에바다 싶으면 걍 안해도 될 듯 싶네요.

아 참고로 저 유일하게 작동하는 테스터는 2년전에 만들어진거라 아마 이전버전 미니쉘이지 않나 싶습니다.

**Comment by yongjulejule** [comment]
<img width="434" alt="Screen Shot 2021-10-02 at 3 08 26 PM" src="https://user-images.githubusercontent.com/79127797/135705665-326780ea-394c-4ae8-ae82-8d95f8bb9b47.png">

<img width="632" alt="Screen Shot 2021-10-02 at 3 08 36 PM" src="https://user-images.githubusercontent.com/79127797/135705670-369f278a-2729-41ab-b043-8dc4ff89529d.png">

저 테스터가 명령어를 실행하고 exit을 한 뒤 exit status를 체크하는 구조이고, 그래서 esh 내에서 258 뜨는건 exit 하면서 & 0xff해서 2가 됩니다. 테스트도 해봤어요.

그래서 마지막 케이스 뺴고 다 맞는건데 맞왜틀???????? 이건 진짜 납득 안되네요

**Comment by 42ghan** [comment]
아하 pwd가 터지는 군요 ㅋㅋㅋ 접수했습니다!

**Comment by yongjulejule** [comment]
<img width="798" alt="Screen Shot 2021-10-02 at 3 25 35 PM" src="https://user-images.githubusercontent.com/79127797/135706100-9276dd04-9310-431e-9f7d-eb0533d56ecb.png">

하하 이거 참! 아무것도 안오고 ; 가 오면 배쉬도 신텍스 에러가 맞는데 배쉬는 환경변수를 굉장히 늦게 해석하나바요;;;

`export TEST=LOL ; echo $TEST$TEST$TEST=lol$TEST` 이런 케이스도 작동이 잘 안됩니다.

근데 저걸 테스트 하던 도중 끔찍한 일이 발생하고 말았어요
<img width="1049" alt="Screen Shot 2021-10-02 at 3 28 56 PM" src="https://user-images.githubusercontent.com/79127797/135706188-bf3c7dab-2076-4832-81ba-e966a5cae0e1.png">




그래서 바로 make debug 하고 다시 시도해보니까 갑자기 터지진 않네요?
<img width="634" alt="Screen Shot 2021-10-02 at 3 29 38 PM" src="https://user-images.githubusercontent.com/79127797/135706204-1a968d94-cafe-4266-98fa-22b2bb0460cd.png">

열받아서 뜰때까지 해봤는데 안뜹니다. 

시한폭탄 쉘이군요. 신난다

**Comment by 42ghan** [comment]
스릴 있네요... 좋다
저도 터질 때까지 테스트 해볼게요 ㅋㅋ

**Comment by yongjulejule** [comment]
#188 에 터질 당시 core dump 파일 찾아서 올려뒀습니다. push_qm에서 터졌다는 소리 같긴 한데 뒤에 숫자는 뭐 어케 해석해야할지 모르겠네요. 혹시 모르니 한번 체크해보세여
