### ISSUE TITLE
Issue : new exec parse problem with \"

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#179]
또 발견해버렸습니다... 화이팅..!
![Screen Shot 2021-10-01 at 9 41 10 PM](https://user-images.githubusercontent.com/83805691/135621462-933721e3-6cd5-4d43-b1f6-5f82aa3f7a7c.png)

확인해봤는데 parse 끝나고 `ls "\\"`으로 넘어갑니다

**Comment by yongjulejule** [comment]
되던게 대체 왜 터지조🤣🤣🤣🤣🤦‍♂️🤦‍♂️

**Comment by yongjulejule** [comment]
얘는 대체 원인을 모르겠네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
"\\" 만 입력하면 \로 인식해서 잘 실행됩니다
ls >"\\" 를 입력하면 역시 파일명 \ 로 리다이렉션 잘 시킵니다
ls "\\" 를 하면 이상해집니다 (?)

쓰다보니 인자로 받을때 문제가 생기는거같네요

찾아보겠읍니다. exit status 테스터만 다 통과하게 만들어두고요

**Comment by 42ghan** [comment]
ㅋㅋㅋㅋㅋㅋ 화이팅 화이팅!
