### ISSUE TITLE
issue : sasohan issue in exit code

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#181]
<img width="699" alt="Screen Shot 2021-10-02 at 9 52 40 AM" src="https://user-images.githubusercontent.com/79127797/135698719-2a3a5763-82fb-46b4-9690-8f84db8116fc.png">

미니쉘에선 리다이렉션 기호만 저런식으로 있으면 에러 메시지를 띄우고 exit status 258이 세팅되어서 괜찮은데
< ; 이렇게 오면 리다이렉션을 그대로 인식해서 파일이 없다고 뜹니다. exit status 1이 세팅되죠

사소하지만 exit status가 bash랑 달라집니다,,, 

<img width="542" alt="Screen Shot 2021-10-02 at 9 55 29 AM" src="https://user-images.githubusercontent.com/79127797/135698770-bdebd0e9-0d1e-417f-af21-f4b97ed194ee.png">
그리고 no such file은 명령어 실행단계에서 리다이렉션 하니 에러 메시지가 복사가 됩니다!

FIXME!!!

**Comment by 42ghan** [comment]
네 이건 고치겠습니다. 제가 오전에 일이 있어서 2-3시 쯤 부터 미니쉘 할 수 있을 것 같아요. 천천히 하세요 ~

**Comment by yongjulejule** [comment]
네 저도 깃헙 액션 써보는중,,, 

얘 이상해요,,, 
```c
void foo(void)
{
    int idx;

    idx = 0;
}
```

이런식으로 쓸모없이 선언해서 아무짓도 안한 애들 다 잡아내네요,,,
ubuntu-latest 환경에서 make 돌리는데 -Werror 옵션이 업데이트 되었나바요,,,

**Comment by 42ghan** [comment]
오 이것저것 해보시고 깃헙액션 나중에 가르쳐주세요 ㅋㅋㅋ 미리 감사합니다

**Comment by 42ghan** [comment]
![Screen Shot 2021-10-02 at 4 09 56 PM](https://user-images.githubusercontent.com/83805691/135707229-0d2154f9-06af-4e91-ba37-57eb8af07d74.png)
틀린 그림 찾기 개꿀잼

**Comment by yongjulejule** [comment]
![hahahaha](https://slack-imgs.com/?c=1&o1=gu&url=https%3A%2F%2Femoji.slack-edge.com%2FT039P7U66%2Ffeelsbadman%2Fc9d62bf6feddb4cf.png)
