### ISSUE TITLE
Issue : using FILE structure

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#184]
`FILE` 구조체를 사용하는게 괜찮을까요?

`stdio.h`에 선언된 구조체이고, stdin, stderr, stdout이 기본으로 설정되어 있습니다

rl_outstream이 file 구조체 자료형인걸 토대로

rl_outstream = stderr을 하면 손쉽게 stderr 프롬프트가 출력됩니다

뭐 안될건 없어보이네요. 코드는 짜놨는데 괜찮으시면 푸쉬 하겠습니다.

지금 푸쉬하면 있는 pr에 합쳐지겠네여

아 그리고 배쉬 소스코드 뜯어보고 알았습니다. 저정도는 그냥 생각해낼법한데 왜 생각을 못했지ㅎㅎ;

참고) stdio man page. 

제가 디버그할때 애용하는 `fprintf`에 항상 첫번째 인자로 주던 그 `stderr`이 `FILE` 구조체입니다
<img width="473" alt="Screen Shot 2021-10-02 at 2 26 02 PM" src="https://user-images.githubusercontent.com/79127797/135704759-a3aa9146-8cc1-4ea7-8226-6e06c60309f7.png">

**Comment by 42ghan** [comment]
`FILE` 구조체 사용 좋습니다!
