### ISSUE TITLE
issue : sub_env

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#195]
execve 직전에 sub_env를 하면서 "$PATH"와 '$PATH'가 구분 안되어 무조건 환경변수로 인식하는 문제가 있읍니다,,,

진짜 노답이네요 ㅎㅎㅎㅎㅎ 

일단 execve 구조를 바꾸고 있는데 바꾸고 나서 생각해볼께요

**Comment by 42ghan** [comment]
아하... 그 앞 단계에서 qm을 없애버려서 그런거죠?...저런... 지금 밖이라 코드를 볼 수 없는데 exec 전에 build structure 하면서 qm 지우기 전으로 sub env를 당기면 되지 않을까 싶긴 하네요.

음... 그럼 새로운 문제가 생길까요? ㅋㅋㅋㅋ해놓으셔도 되고, 어차피 제가 rm/expand qm을 exec 쪽으로 옮길 거여서 저녁에 제가 한꺼번에 해도 됩니다

**Comment by yongjulejule** [comment]
요리조리 바꿔봤는데 노답이네여 ㅎㅎ;  일단 냅두겠습니다

**Comment by yongjulejule** [comment]
<img width="1232" alt="Screen Shot 2021-10-03 at 4 31 16 PM" src="https://user-images.githubusercontent.com/79127797/135744440-3dac1aa5-f686-4bcd-bba1-84b66edd9603.png">

제가 바꾸다가 조건 잘못준건지 터지네요? 웃긴건 테스트 320개 돌아가는동안 한번도 안터졌단겁니다 어이업네 ㅎㅎ;

뭐 처음 돌려봤을때 25*/320에서 271/320로 대단히 발전했읍니다,,,

그리고 많은 경우에 $12TEST 이런거 테스트라서 $1? $12? 를 지우도록 요구하는데 저건 틀렸다고 냅둬도 될 것 같아요 ㅎㅎ;

**Comment by yongjulejule** [comment]
아 이거 제가 고쳤읍니다
