### ISSUE TITLE
Issue : New Tester! single quote interpret "everything" as character

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#200]
[link](https://github.com/potatokuka/mini_tester)
ㅎㅎ 신나네요 굉장히 많이 테스트 합니다.

1270개중에 313개 틀리는군요

exit status 139찍히는 이상한게 있어서 돌려보니까 segfault 더라구요? ㅎㅎ SIGSEG 시그널이였네요 ㅎㅎ 아 신난다

<img width="1425" alt="Screen Shot 2021-10-03 at 5 52 08 PM" src="https://user-images.githubusercontent.com/79127797/135746614-90465015-51a7-4dfe-95d0-c8bd67ae1d67.png">

뭐 제가 넣어본건 이거고

대체 왜떄문에 bash는 echo '\' 를 하면 \ 가 출력될까요? 진짜 너무 어이없다

더 테스트 해보니까 '는 진짜 모든 문자를 그대로 해석해서 \가 고대로 나오네요/>???????? 어이없어 상상도 못했어 ㄴㅇㄱ
<img width="269" alt="Screen Shot 2021-10-03 at 5 55 27 PM" src="https://user-images.githubusercontent.com/79127797/135746700-87350bba-c954-4707-980e-93fbe695b944.png">

**Comment by 42ghan** [comment]
아 저 segv는 인지하고 있습니다...bash...또 맘에 안드네요...

**Comment by 42ghan** [comment]
`echo "'"`는 고쳤습니다!
![Screen Shot 2021-10-04 at 1 01 08 AM](https://user-images.githubusercontent.com/83805691/135762103-7c9e978d-c92c-4b44-ac83-f8ca512b0e17.png)

**Comment by 42ghan** [comment]
이 또한 bash 는 틀렸지만 bash 와 같이 파싱하게 바꿨습니다.
![Screen Shot 2021-10-04 at 12 50 52 PM](https://user-images.githubusercontent.com/83805691/135790170-6bdbdd2f-3b7a-417d-bace-9e26626084e8.png)
