### ISSUE TITLE
Issue : parse error

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#208]
<img width="510" alt="Screen Shot 2021-10-04 at 2 28 29 PM" src="https://user-images.githubusercontent.com/79127797/135798674-cc632334-8e9f-4533-9537-b34ffe36406c.png">

백슬레쉬 하나당 맨 끝 문자가 하나씩 사라집니다! 배쉬가 아니라 베니쉬쉘 ㅎㅎ;

그리고 이거는 납득이 진짜 안되는데
<img width="390" alt="Screen Shot 2021-10-04 at 2 29 55 PM" src="https://user-images.githubusercontent.com/79127797/135798790-16f6fba3-3cfc-4b88-88c6-65d5c9a751dc.png">
`/Users`를 입력하면 yongjule가 뜹니다?! /Users에 yongjule 폴더가 있어서 그런건지... 권한 있는 폴더만 가져온건가? 다른 분들 폴더도 엄청 많은데

다른 디렉토리는 저런거 없습니다.

뭔가 제쪽에서 문제같긴 한데 암튼 이런 문제가 있습니다

밑에꺼부터 찾아보겠읍니다

**Comment by 42ghan** [comment]
오홍 배니쉬...쉘... 위에 거는 제가 봐볼게요

**Comment by yongjulejule** [comment]
하하ㅏ하 찾았읍니다 하하하ㅏㅎ하ㅏㅎ

/usr/bin/Users라는 바이너리가 존재했고, /User라고 넣으면 /usr/bin//User로 인식되어서 그랬던 것입니다.

따라서 /ls /cat /pwd ... 등등이 너무나도 잘 실행이 됩니다! 히히하하핳하 ㅏ신난다

암튼 원인을 찾았으니 처리해보겠습니다

**Comment by yongjulejule** [comment]
<img width="347" alt="Screen Shot 2021-10-04 at 2 40 38 PM" src="https://user-images.githubusercontent.com/79127797/135799658-0b24b60c-ec42-41b3-8463-340c807a62fd.png">
이런 버그도 있습니다,,,

그리고 이것저것 해보니 /는 \/ 이렇게 와도 /를 디렉토리라고 그냥 인식하더라구요? 뭐 덕분에 처리하긴 쉬워졌지만 요상한 특징을 알아버렸습니다. 
파일명에 / 는 못넣는것 같더라구요. touch \/abc 이렇게 해도 루트디렉토리에 만드려고 해서 클러스터에선 퍼미션 디나이드가 뜹니다 ㅎㅎ

**Comment by yongjulejule** [comment]
@42ghan 
<img width="414" alt="Screen Shot 2021-10-04 at 3 02 48 PM" src="https://user-images.githubusercontent.com/79127797/135801507-cc525180-1c62-435a-b352-f39e3b68d39c.png">

무언가 잘못되었습니다~~~~~~

**Comment by 42ghan** [comment]
아 제발...

**Comment by yongjulejule** [comment]
<img width="1277" alt="Screen Shot 2021-10-04 at 3 12 51 PM" src="https://user-images.githubusercontent.com/79127797/135802238-ee997ce6-c50f-40ce-a7b0-55f749a22ba1.png">

하하 신난다! 이건 제가 할께여 ㅎㅎ;
<img width="1279" alt="Screen Shot 2021-10-04 at 3 13 37 PM" src="https://user-images.githubusercontent.com/79127797/135802308-ed140682-4584-4e73-b0cf-86e0258fc331.png">

-n 이 ㅇ오면 n이 몇개가 와도 -n옵션으로 인식합니다
만약 n이 아닌 문자가 하나라도 있으면 그냥 출력하고, 그 이후에 나오는 -nnnnnnnnnn 도 문자로 인식해서 출력합니다
