### ISSUE TITLE
Issue : it worked but now... 😅

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#214]
<img width="323" alt="Screen Shot 2021-10-04 at 4 59 37 PM" src="https://user-images.githubusercontent.com/79127797/135814728-3b7580c6-7c31-42ee-a6e3-696272d8adee.png">

예... 파싱이 바뀌더니 되던게 안되어서 지한님이 파싱했던 부분에서 저렇게 넘어옵니다.... 그냥 ls;ls;ls; 이런건 잘되는데 따옴표 들어가면서 이상해지네요

![hahaha](https://emoji.slack-edge.com/T039P7U66/feelsbadman/c9d62bf6feddb4cf.png)

**Comment by 42ghan** [comment]
고치겠습니다~
