### ISSUE TITLE
Issue : rdr error(?)

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#216]
syntax error 잡다가 에러를 발견하고 말았습니다...

`>` 다음에 `|` 나오면 rdr이 작동해야하는 것 같습니다...ㅠㅠ
![Screen Shot 2021-10-04 at 6 09 54 PM](https://user-images.githubusercontent.com/83805691/135824779-faef7aa3-6b87-46b5-95f9-d62839a37e28.png)

그리고 저희가 &/&&을 안 하기 때문에 &이 들어가면 일반 char로 인식해야 하는데 아마 rdr parsing 쪽에서 rdr 기호로 인식하는 것 같습니다...
![Screen Shot 2021-10-04 at 6 11 59 PM](https://user-images.githubusercontent.com/83805691/135824977-38eb0176-f809-4475-a0f2-b374db40f99e.png)

내일 클러스터 갑니다. 내일 같이 잡으시죠 ㅋㅋㅋㅋ

**Comment by yongjulejule** [comment]
아 &는 쉽게 잡을수 있어요 그리고 >| 는 특정한 리다이렉션을 뜻하는걸로 기억하는데 뭔진 기억이 안나네요…

**Comment by 42ghan** [comment]
아 맞다 >| 이거 안 하기로 했었던 것 같네요 ㅋㅋㅋㅋㅋ 좋습니다 👍 ㅋㅋㅋㅋ

**Comment by yongjulejule** [comment]
찾아보니 쉘 빌트인 옵션으로 noclobber옵션을 줄 수 있는데, 얘를 주면 > 리다이렉션으로 파일에 덮어쓰기가 불가능 하다고 하더라구요? 이때 덮어쓰는 목적으로 >| 리다이렉션을 쓴다고 합니다. 구현 불가 땅땅땅 걍 >랑 똑같이… 처리할까 생각했는데 저희는 파이프가 분리되서 쉽진 않겠네요? 흠 생각해봐야겠어요

**Comment by yongjulejule** [comment]
아님 걍 냅둘까요? ㅎㅎ 그래도 될 것 같고

**Comment by yongjulejule** [comment]
사진 보니까 아주 그냥 정직하게 커멘드를 잘 수행했네요 ㅎㅎ!

**Comment by 42ghan** [comment]
걍 냅두는 걸로 땅땅땅 ㅋㅋㅋㅋ
