### ISSUE TITLE
Doc : Custom Exit code range

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#226]
-4242는 &0xff하면 110이라 괜찮겠네여~~~

<img width="212" alt="Screen Shot 2021-10-06 at 2 43 18 PM" src="https://user-images.githubusercontent.com/79127797/136146810-d6faad35-4479-4284-812c-0efb5cd73c23.png">

[ref](https://unix.stackexchange.com/questions/604260/best-range-for-custom-exit-code-in-linux)

**Comment by 42ghan** [comment]
![Screen Shot 2021-10-06 at 2 45 23 PM](https://user-images.githubusercontent.com/83805691/136147044-cff6085f-b4e7-4176-9210-bff8c9039848.png)
parse.h에 이 것 때문에 걱정하시는 거면 괜찮습니다. 단지 flag로 쓰고 각자 258, 1 로 바꿔줍니다.

**Comment by yongjulejule** [comment]
아 저도 하나 써서 검색해봤다가 남겨둔거에여~~
