### ISSUE TITLE
Issue : Tester log in echo... 🤷🙋🤦

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#239]
첫번째 사진은 테스터에서 가져온 로그고, 두번쨰는 구분을 쉽게 하기 위하여 공백을 핑크색으로 표시해둔 겁니다.

아 이건 -C로 실행하는 테스터에서 가져온겁니다. 얘가 증믈 그믑게도 다양하게 테스트 하더군요

<img width="643" alt="Screen Shot 2021-10-10 at 12 02 54 PM" src="https://user-images.githubusercontent.com/79127797/136679925-a1659fbf-ab12-48fd-ab3e-b3c67a62dcb5.png">
<img width="642" alt="Screen Shot 2021-10-10 at 12 03 08 PM" src="https://user-images.githubusercontent.com/79127797/136679938-6eabf21d-aea9-42fd-acb0-ec2e1355ef50.png">

66번을 보고 너무 어이없어서 테스트해본건데 진짜루 넘 어이없네요
<img width="370" alt="Screen Shot 2021-10-10 at 12 04 28 PM" src="https://user-images.githubusercontent.com/79127797/136679990-c61fb332-20b6-4940-b66e-3710e85092cc.png">
<img width="255" alt="Screen Shot 2021-10-10 at 12 04 41 PM" src="https://user-images.githubusercontent.com/79127797/136679995-439624bc-bc68-4846-860b-6ae69308b998.png">

**Comment by 42ghan** [comment]
아이고 두야... 감사합니다...ㅋㅋㅋㅋㅋㅋㅋㅋ #BASH_IS_WRONG

**Comment by yongjulejule** [comment]
저도 차근차근 해결해볼께여~~~~

**Comment by yongjulejule** [comment]
일단 ""는 "\0"로 인식하여 인자는 있지만 아무것도 아닌걸로 판단하는것 같읍니다,,, argv로 다 넘겨줘야할듯? 으갸갹

그리고 마지막 70번 케이스는 quotes가 덜닫힌 사례입니다. 잘못가져왔네요. 다행!

**Comment by yongjulejule** [comment]
아 저것도 비슷한 문제였겠네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 굳굳
