### ISSUE TITLE
envp = 0... fix tmr

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#43]
![Screenshot_20210912-221215_GitHub.jpg](https://user-images.githubusercontent.com/83805691/132988891-11833317-89d8-46e4-b2a6-3ddf740325c7.jpg)

ㅋㅋㅋㅋ 테스트하면서 envp = 0 해놨네요
내일 고치죠

**Comment by yongjulejule** [comment]
ㅋㅋㅋㅋㅋㅋ 알겠습니당
