### ISSUE TITLE
issue : AddressSanitizer SEGV or heap-buffer-overflow

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/minishell#49]
1) cmds = {"|;", NULL}. SEGV
<img width="1086" alt="Screen Shot 2021-09-13 at 4 52 15 PM" src="https://user-images.githubusercontent.com/83805691/133045061-ad276810-1d45-438a-b75e-69a6400fa845.png">

2) cmds = {"\"\"", NULL}, heap-over-flow
<img width="1100" alt="Screen Shot 2021-09-13 at 4 50 26 PM" src="https://user-images.githubusercontent.com/83805691/133044787-d0e1d4f3-8bda-422c-b0f0-624545ab7c56.png">

**Comment by yongjulejule** [comment]
![img](https://i.kym-cdn.com/entries/icons/original/000/002/830/sad_frog.jpg)

**Comment by yongjulejule** [comment]
해결!
