### ISSUE TITLE
Idea : execute built-in cmds

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#60]
예전부터 생각하던건데 말씀 드린 기억이 없어서 남겨놓습니다.
저희가 명령어를 실행할때 execve함수를 사용하잖아요? 근데 built-in 명령어를 실행한다고 생각해보면, execve 함수 직전까지 로직(파싱,,, 파이프,,, 등등)이 모두 동일하고 실행하는 명령어만 달라지니 함수 포인터를 사용하여 빌트인일때 / 나머지 명령어일때 해당하는 함수를 구조체에 넣어둬서 그때그때 적절한 함수로 실행 시킬수 있으면  좋을것 같네요. 

말 했던것 같기두 하고 아닌것 같기두 하고 파싱하기 싫어서 갑자기 이러고 있는건 맞고 암튼 그렇습니다. 리다이렉션 드릅게 어려운데 리스트 함수들 만들 생각하니까 머리도 아프네요 ㅎㅎ;;

그러면, execve함수와 동일한 방식으로 작동하면 참 좋겠죠? 
`int execve(const char *path, char *const argv[], char *const envp[])`
프로토타입이 이런식으로 생겨먹었고 똑같이 해주면 될 것 같구, 성공시 해당 커맨드처럼 작동시키고 `exit(EXIT_SUCCESS)`, 실패시 `return -1` 해주면 참 좋을것 같습니다. 필요하면 적절한 `errno`로 직접 세팅해주면 더 재미있을 것 같네요 ㅎㅎㅎ

**Comment by 42ghan** [comment]
좋은 아이디어 감사합니다 :D
