### ISSUE TITLE
Bash source code use readline

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#69]
대체 bash는 파싱을 어떻게 하지????????? 라는 의문으로 소스코드를 찾아 봤는데 흥미로운 점을 찾았읍니다.

일단 배쉬도 `readline` 라이브러리를 사용하더라구요? 그래서 `SIGINT` 핸들링 부분이 떠올라서 얼핏 봤는데,

그렇읍니다.. bash도 `fflush` 함수로 플러쉬 시키는거 같네요 ㅎㅎ;; 노답

여담으로 파싱은`swich`문이란 아주 좋은 조건문을 활용하여 파싱하더라구요 하하핳핳신난다 미친놂고양이 ㅎㅎㅎㅎㅎ

궁금하실까봐 밑에 bash 소스코드 링크 남겨드립니다. 구글링하면 10초안에 나오긴 하는데 찾기 귀찮잖아요 ㅎ

1. event handling 하는 부분
<img width="979" alt="Screen Shot 2021-09-18 at 9 46 52 AM" src="https://user-images.githubusercontent.com/79127797/133866491-c9a46468-170b-4695-b49a-e3999173a134.png">

2. SIGINT에 해당하는 조건문으로 들어갔을때 
<img width="821" alt="Screen Shot 2021-09-18 at 9 47 01 AM" src="https://user-images.githubusercontent.com/79127797/133866496-14672548-a0a7-4453-b780-b8313088efd5.png">

3. buffer flush!
<img width="795" alt="Screen Shot 2021-09-18 at 9 47 11 AM" src="https://user-images.githubusercontent.com/79127797/133866495-563916bb-ac29-45e1-814f-3be057d40556.png">

[bash source code (download link!)](https://tiswww.case.edu/php/chet/bash/bashtop.html#Availability)

**Comment by 42ghan** [comment]
ㅋㅋㅋㅋㅋ ft_fflush ft_switch 만들어보죠
