### ISSUE TITLE
Issue : Error Message

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#79]
에러 메시지를 배쉬랑 똑같이 맞춰줘야 할까요??

파펙스에서는 그렇게 하라고 되어있었는데, 미니쉘에는 그런 문구가 없네요.

에러 메시지가 
`command not found : [입력한 커맨드]`
`ambiguous redirection : [입력한 이상한 파일디스크립터]`
`no such file or directory : [open 하고자 한 파일명]`
이런 식이라 쉘에 있으면 확실히 도움이 되는 부분인데
맞춰주자니 파싱하고나서 버릴 데이터들을 계속 들고 있어야 해서 피곤하고
안맞추자니 완성도가 넘 떨어지는거 같아 찝찝한데
어떻게 생각하시나요? 

사실 위에 제가 써놓은 정도는 맞춰주려고 하는데 (대부분은 끝까지 들고가는 데이터들이라 맞춰주기 쉽습니다 하지만...)

아래와 같이 특정 기호가 의미있는 symbol인지 체크해서 에러 메시지를 띄우는 경우가 있는데
<img width="507" alt="Screen Shot 2021-09-19 at 10 01 51 AM" src="https://user-images.githubusercontent.com/79127797/133912235-7360926a-4318-4d6c-b78d-7dd7651d99e0.png">
저런거 맞추기는 쉽지않단 말이죠... 구조를 함 갈아엎으면 할만한데,,, 암튼요!

적당히 맞추는 선에서 타협할까요? ㅎㅎ 아님 다 맞춰볼까요? 

다 내비두고 일단 돌아가게 만드는게 우선이겠죠? 혼자 결론이 나긴 했네요 ㅎㅎ 암튼 의견 주세요

**Comment by 42ghan** [comment]
똑같이 맞출 필요는 없지만 기준으로 삼고 비슷하게 만들면 되지 않을까 싶네요. syntax error는 parsing 쪽에서 handle 할 수 있습니다. 이미 ;나 | syntax error 는 처리 해놨어요. Syntax error 발견하신 case들 기록만 해주시면 큰 도움이 될 것 같네요 :)

**Comment by yongjulejule** [comment]
그럼 에러케이스 생각하면서 짜고 있는데, 그때그때 찾아보면서 에러케이스 확인하는거라 가물가물하니 코드를 마저 짜고 이따 정리해놓겠습니다.

그리고 리다이렉션 어떤게 있는지 정리해놨던 이슈 위키로 옮겼습니다... 간지나더라구요 ㅎ

**Comment by yongjulejule** [comment]
아 그리고 방금 확인해보니 에러메시지가, syntax error 같은 경우는 한 라인 모두에서 한번만 나오고
command not found, no such file 이런 에러는 파이프 하나 하나에 맞춰 나오네요. 
syntax error도 커멘드 하나에 한번씩 나올줄 알았는데 아니였네요. 파싱 과정에서 처리해도 무방할듯요!

글로는 이해가 잘 안될 것 같아서 이해를 돕기 위한 사진입니다

<img width="512" alt="Screen Shot 2021-09-19 at 11 12 53 AM" src="https://user-images.githubusercontent.com/79127797/133913204-8c5257b5-5ea9-4d04-9d82-f5d84611427a.png">

syntax error는 한번뜨면 끝

<img width="483" alt="Screen Shot 2021-09-19 at 11 13 28 AM" src="https://user-images.githubusercontent.com/79127797/133913211-da0d9aa4-3d67-4dbb-9590-4cb559a1e337.png">

프로세스 실행중의 에러(?) 는 매번 검증해서 뜸

**Comment by 42ghan** [comment]
네 맞아요 syntax error는 parsing에서 잡고 error시 cmds==NULL로 해서 exec 부분에서 걸러지게 하는게 맞을 것 같아요. 저도 rdr split하는데 어차피 좀 걸리니까 천천히 시간 되실 때 error piling 부탁드립니다. 감사합니다 :)
