### ISSUE TITLE
Issue : Redirection Parsing error list in bash

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#86]
터트려 달라고 하셔서 터트려 보았읍니다...

#67 에서 첫 줄에 써놓은 10개의 리다이렉션에 `&, >, <` 을 덧붙이면 거의 대부분 syntax error를 벹더라구요?
`>>>, <<<` <-이 아이는 bash에 원래 있는데 저희가 구현 안한거니 저희는 적절한 메시지를 출력해야 할 것 같고
이 외에 `<<&, >&>, &<&` 이렇게 원래 있던 리다이렉션에 기호들이 추가되면 bash도 syntax error를 뱉고 저흰 터집니다 ㅎ

근데 제가 하는 부분에서도 에러처리 가능할 것 같은데 머리아프시면 제가 해도 됩니다.
어차피 제 부분에서 #67 에 언급한 모든 리다이렉션을 테스트 하고, 모두 해당하지 않으면 errorflag로 뒀기 때문이죠

진짜 할만 할 것 같은데? 암튼 그렇습니다.

그리고 터지면 종료코드 SIGABRT 이런식으로 세팅되는거 너무 신기하네요 ㅎㅎ;
근데 배쉬는 128 + signal number 로 exit_code가 설정되어서 이건 바꿔놔야겠네요.

여담이 길어졌네요 더 해보려다 제쪽에서 터지는거 발견해서 고치러 갑니다 총총총,,,😅

아 제 쪽에선 리다이렉션 기호만 딱 들어왔을때 터집니다.  `>` 이렇게 하나만 입력될때 말이죠. 지한님쪽 잘못은 아니니까 참고해주세요  

<img width="494" alt="Screen Shot 2021-09-20 at 8 56 11 AM" src="https://user-images.githubusercontent.com/79127797/133947101-9ef56224-07b8-4da2-9cf8-dd9f719c7f34.png">
<img width="494" alt="Screen Shot 2021-09-20 at 8 56 22 AM" src="https://user-images.githubusercontent.com/79127797/133947107-9f59ab09-33db-4c11-bdd0-09dad9398b14.png">
<img width="473" alt="Screen Shot 2021-09-20 at 8 57 02 AM" src="https://user-images.githubusercontent.com/79127797/133947133-59f87c96-ed9f-41da-93cc-727402945996.png">
<img width="1418" alt="Screen Shot 2021-09-20 at 8 58 01 AM" src="https://user-images.githubusercontent.com/79127797/133947152-54f879f6-bac8-4886-9f8c-45d857c70ea6.png">
<img width="473" alt="Screen Shot 2021-09-20 at 8 58 34 AM" src="https://user-images.githubusercontent.com/79127797/133947163-8ca53151-b9b7-424b-9b0e-e9ed801159a9.png">

**Comment by 42ghan** [comment]
아 테스트 해주셔서 감사합니다. 지금 정상적인 input이 아니면 왠만하면 터질 거예요. 특히 '&'이 들어갈 경우 불안합니다 ㅋㅋㅋ Syntax error로 처리하는게 어려운게 아니라 모든 케이스에 적당한 사이즈로 할당해서 split하는게 쉽지 않네요. Syntax error는 cmds로 split 한 후에 해결할 생각입니다.

테스트 하시면서 또 터지는 경우 있으면 알려주세요 :)

**Comment by yongjulejule** [comment]
try / exception 구문은 왜 c에 없을까요? 있었으면 정말 편했을텐데 그쵸? 하지만 있다고 42에서 쓰게 해줄까요? 저는 아니라고 봅니다. 멀쩡한 쉘이 얼마나 많은데 쉘을 만들으라 하는거 보면 정상이 아녜요 그쵸? 히히 신난다 꺄하핳 저 좋은걸 안만들다니 데니스 리치 당신은 틀렸어

**Comment by yongjulejule** [comment]
\>a  -> 터집니당!
<img width="750" alt="Screen Shot 2021-09-20 at 10 59 20 AM" src="https://user-images.githubusercontent.com/79127797/133950922-020581f2-b37f-4411-b21f-24a0f84a5321.png">

**Comment by 42ghan** [comment]
아 또 터지네 ㅋㅋㅋㅋㅋ
switch도 못 쓰게 하는대요 뭘 ㅋㅋㅋㅋㅋㅋ 아 파싱 좀 구조를 바꿀 생각입니다. 지금까지는 ft_split을 변형하면서 어떻게든 한번에 해보려고 했는데 char** 할당 사이즈 재는게 너무 복잡해지네요. 코드 줄 수는 좀 더 짧을지 몰라도 점점 설명할 수 없는 코드가 되는 것 같아요 하하... 

그래서 바꾸는데 좀 시간이 걸리겠지만 char** 할당 사이즈 신경 안 써도 되게 연결리스트에 먼저 담으려고요. ;| 기준으로 한번 split하고 그 다음에 rdr기호 기준으로 split한 후에 연결리스트 -> char**. 이렇게 단계를 나누는게 그나마 더 깔끔하고 효율적인 코드가 될 것 같네요.

오늘은 광주 내려가야해서 내일부터 본격적으로 할 수 있을 것 같습니다...  esh 화이팅!

**Comment by yongjulejule** [comment]
맞아요 리스트 추천드립니다... 제 부분에서도 배열의 한계를 느껴서 리다이렉션 부분은 다 리스트로 처리했어요!

조심히 내려가시고 내려가셨으면 좀 쉬다 오세요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저두 내일부터 러쉬평가 가니까 ㅎㅎ 화이팅~!~!!

**Comment by yongjulejule** [comment]
`>&, <&` 같이 & 다음 무언가 와야 하는데 안오는 경우

<img width="567" alt="Screen Shot 2021-09-20 at 4 53 22 PM" src="https://user-images.githubusercontent.com/79127797/133971224-beb0e2c1-3df5-4632-b855-f7182099c949.png">

`>&[아무 글자 숫자 다 가능]`, `<&[숫자만 가능]`

<img width="446" alt="Screen Shot 2021-09-20 at 4 53 51 PM" src="https://user-images.githubusercontent.com/79127797/133971268-16e49973-62ef-4ca9-aab2-ccf7270e6d39.png">

**Comment by yongjulejule** [comment]
`<&-` `>&-` 얘네도 하시나요??
만약 하신다면 마지막 `-` 기호까지가 리다이렉션 끝이고, `[fd]<& -abc` 이렇게 오면 fd를 닫고, 커멘드 abc를 실행하라는 뜻이 됩니다.

<img width="362" alt="Screen Shot 2021-09-20 at 5 01 01 PM" src="https://user-images.githubusercontent.com/79127797/133971967-4fbf72fc-8584-4636-9d44-f1f68a6338b8.png">

`[fd_1]<&[fd_2]-` 의 형태로 확장될 수 있으며, 각 fd는 무조건 숫자여야 합니다,,, 이것까지 해야하나 싶긴 해요. 

<img width="293" alt="Screen Shot 2021-09-20 at 5 02 30 PM" src="https://user-images.githubusercontent.com/79127797/133972160-65a29b63-2d9a-4d28-a6cc-d84e084f5947.png">

여기서 b는 커맨드 취급입니다!

**Comment by 42ghan** [comment]
아 까도 까도 끝이 없는 양파 같은 리다이렉션의 세계...

Subject에서 요구하는 건 <, >, <<, >> 만 핸들하는 것 같기는 해요. 일단 파싱은 다 해서 넘기겠습니다.

<, <<, >, >>, >&, &>, <&, <>, <&-, >&-

지금까지 용줄레님이 구현하신 부분에서 위 10개 기호 모두 처리하셨나요? 구현하신 케이스는 일단 하는 걸로 하고, 아직 안 돼있다면 체력과 정신 건강이 허락한다면 하는 걸로 우선 순위를 미뤄두죠 ㅋㅋㅋㅋㅋㅋ

그리고 파싱 단계에서는 syntax error만 잡는게 맞을 것 같습니다.

**Comment by yongjulejule** [comment]
네 다 처리하긴 했는데 `<&[fd]-` 이런 경우는 안해놓긴 했어요. 이 부분 힘드시면 패스하는걸로
