### ISSUE TITLE
issue : exit status

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#89]
bash에서는 exit status가 255를 넘지 않는다고 합니다. 8비트만 쓴다고 하더군요

[ref : bash exit status list](https://tldp.org/LDP/abs/html/exitcodes.html)

근데 왜 대체 syntax error는 exit status 258을 뱉는 걸까요?

아무리 구글링해도 안나오네요

실제로 bash에서 `exit 256`을 하면 0이뜨고, `exit 257`을하면 1이 뜹니다.

[ref : exit status above 255 ](https://www.baeldung.com/linux/status-codes)

255를 넘는건 -256를 하고 보면 된다고 하긴 하고, 그래서 syntax error = error status 2 라고 보면 말은 되긴 합니다.

얘를 그대로 구현하는게 맞나 싶네요

뭐 급한건 아니니 나중에 생각해보죠.

**Comment by 42ghan** [comment]
오... 신기하네요 누군가 이런 걸 다 정해뒀다니... 그런데 우리가 이걸 구현해야 한다니... ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
