### ISSUE TITLE
Issue : About Signal

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#90]
bash 에서 명령어를 실행하기 전이 SIGINT를 받으면 exit status = 1로 세팅됩니다. 

fork를 하고 exec()를 하면 exec()를 통해 /bin/ls 이런걸 실행해도 시그널 핸들러는 그대로 가져갑니다.

명령어 실행중 signal을 받으면 exit_code = 128 + signal number 로 세팅되기 때문에, g_exit_code를 수정해줘야 합니다.

여기까지는 명령어 실행 단계에서 signal handler 를 이용해서 어찌어찌 바꿔보겠습니다

그리고 sigquit는 coredump 파일을 생성한다고 합니다... 으어어... 빌트인 짜기 전에 저거도 좀 처리 해보겠습니다

시그널 건드리다가 어디 이상해질지 모른다는 걱정에 남겨놓습니다. 터지면 지한님이 고쳐주시겠죠~!@~!!

**Comment by 42ghan** [comment]
아... 시그널 핸들러까지 가져간다니... 정말 노땡큐네요... ㅋㅋㅋㅋㅋ 걱정말고 바꿔보세요 ㅋㅋㅋㅋ 우리에겐 git reset --hard 가 있으니까요!

방금 찾아보니까

![Screenshot_20210920-140856_Chrome.jpg](https://user-images.githubusercontent.com/83805691/133959269-d12b6a6c-27ac-4d07-9b18-0003461de804.jpg)
![Screenshot_20210920-141206_Chrome.jpg](https://user-images.githubusercontent.com/83805691/133959291-be2086d1-cdca-4b23-be5a-7a2baad4488c.jpg)

fork한 process에서 Execve 전에
`signal(SIGINT, SIG_DFL);
signal(SIGQUIT, SIG_DFL);`
해주는게 해답이 될 수도 있겠네요!

https://stackoverflow.com/questions/14528278/delete-a-linux-signal-handler-in-c

**Comment by yongjulejule** [comment]
오 와우 감사합니다 
![img](https://emoji.slack-edge.com/T039P7U66/amaze/43597fb9eac4d325.gif)

**Comment by yongjulejule** [comment]
리셋하고 SIGQUIT을 주니까  core dump 파일까지 생성하네요? 대박신기해요  `~/Library/Logs/DiagnosticReports` 이 디렉토리에 여태 터진기록이 다있어요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 

근데 core dump 파일을 진짜 쉘처럼 저희 미니쉘 디렉토리에 생기게 하면 정말 멋지겠단 생각이 드는데 쉽지 않네요 ㅎ 조금만 해보고 안된다 싶으면 걍 넘어갈께요.
