### ISSUE TITLE
Issue : env in single quote

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#93]
<img width="282" alt="Screen Shot 2021-09-20 at 5 42 03 PM" src="https://user-images.githubusercontent.com/79127797/133976440-057ff23e-9653-4e35-9685-826415bd55d8.png">

작은 따옴표에 [$환경변수]만 들어있는 경우 환경변수로 읽어버리네욤.. ㅎ;;

**Comment by 42ghan** [comment]
아 저런.. 고칠게요 ㅋㅋㅋㅋㅋㅋㅋ
