### ISSUE TITLE
Issue : minishell on minishell on minishell...

### ISSUE THREAD

**Issue by yongjulejule** [brilliantshell/minishell#98]
<img width="357" alt="Screen Shot 2021-09-21 at 10 47 42 AM" src="https://user-images.githubusercontent.com/79127797/134099891-bbf94a94-afba-46b5-8c4c-28a3c20cb293.png">

미니쉘 위에 미니쉘 위에 미니쉘이 올라오면서 입출력 스트림이 이상해짐...!
또한 입력도 여러번 받고, exit하면 한번에 싹다 exit됨. 
시그널도 한번에 여러번 받는 등 문제가 심각함..

이건 프로세싱쪽 문제같긴 한데 미니쉘에서 미니쉘을 실행하면 이전 미니쉘은 입출력을 다 막아버려야 하나..? 시그널도...? 근데 막고 나면 회복이 가능한가?

두 미니쉘을 완전히 분리해야 할텐데...

아 아니면 여기서 새로운 tty를 열어서 쓰나...? 그런것 같기두 하고

쉽지 않네요

**Comment by 42ghan** [comment]
시그널은 `signal(SIGINT or SIGQUIT, SIG_IGN)`를 먼저켜진 shell에 적용하면 될 것 같은데 입출력...은 특정 process의 입출력을 잠시 막는 방법을 좀 찾아봐야겠네요. termios 함수들이나 ioctl 사용하면 방법이 있을 것 같은데 검색해보겠습니다. 토요일에 클러스터 갈 계획인데 그 때 나오신다면 이 부분은 만나서 해결해도 될 것 같네요.

**Comment by yongjulejule** [comment]
글게요 방법이 있을거 같은데 고민좀 해봐야겠네요 으아
